# SchoolService-deployment.yaml
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: school-v10
spec: 
  replicas: 1 
  selector:  
    matchLabels:  
      app: schoolapp
      version: "v10"
  template:  
    metadata: 
      labels:
        app: schoolapp
        version: "v10" 
    spec:
      containers: 
      - name: schoolapp 
        image: abucontainerregistry.azurecr.io/schoolservice:v10
        ports:
        - containerPort: 8800
          name: https     
        
---
# SchoolService-service.yaml
apiVersion: v1
kind: Service
metadata: 
  name: schoolservice
  labels:
    app: schoolapp
spec:
  ports:
  - port: 8800
  # targetPort: 8900
    name: https
  selector: 
    app: schoolapp
        